### ISSUE TITLE
If you break it you buy it...

### ISSUE THREAD

**Issue by d-k-k** [uhmlavalab/SIEGE#13]
Ok.... spent the entire afternoon bug fixing and making sure that the program actually launched and ran only to find that the latest pull crashes on launch.

Run index.html in Firefox before you commit / push. If you can't get to the game screen where stuff moves, check the console for errors and ideally fix them.

Maybe its a simple fix. I actually didn't bother looking this time. Done working on this for tonight.

**Comment by m-she** [comment]
So tried running index and found some arrows that github inserted was
preventing me from reaching the title screen. I removed those, and I think
it should work now.

**Comment by m-she** [comment]
Also, I don't really have any task to do for the entities, is there
something I should work on or anything I should help with?

**Comment by d-k-k** [comment]
Good, thank you for fixing it.

Basically ask yourself "what is missing from the prototype?"
All those things are available to work on if not claimed by someone.

Ex:
invader creation and placement. (work with Vitor)
hooking invaders with their ai. (work with Eric)
score display, counter. Is score implemented in any form? ( unclaimed? )
checking that entities work correctly: players, invader, shots. 
The assets for start, game over, explosion are in the folder. Is the game mechanically ready to use them?
etc.
